name: jsifier
description: convert JS objects into Dart maps and lists
version: 2.0.0
author: John Ryan <john.p.ryan4@gmail.com>
homepage: http://github.com/johnpryan/jsifier

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  js: ^0.6.0

dev_dependencies:
  test: ^1.3.0
